spring.application.name=DigitalDiary

server.port=9090 

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/digitaldiary
spring.datasource.username=postgres
spring.datasource.password=nic123

# Optional settings (used with Spring Boot JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.view.prefix=V:\\Java workspace\\SmartDairy\\src\\main\\resources\\templates
#spring.web.resources.static-locations=V:\\Java workspace\\SmartDairy\\src\\main\\resources\\static\\images
spring.mvc.view.suffix=.html
spring.thymeleaf.enabled=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartdairynoreply@gmail.com
spring.mail.password=jfxgdebtrqyebcub
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2



logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
spring.mail.properties.mail.debug=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


